### ISSUE TITLE
Create dbt tests to ensure data quality 

### ISSUE THREAD

**Issue by DistributedDoge** [davidgasquez/gitcoin-grants-data-portal#20]
dbt allows for `schema` testing, where we can declare what we want to see, and run `dbt test` to see if reality conforms to expectations.

```
models:
  - name: orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
```

I think it is worthwile to create those for some important models. Since we are already describing schema it would be nice to also:

- tag all `addresses` so we know at glance if for example `round_id` is actual address or just random string.
- make sure all addresses conform to `is_lowercased` test for consistency.

Ultimately, we could have a `dbt test` added as CI step to make sure that runs with malformed or missing assets do not proceed to IPFS upload stage.
